var userImageUrl;
var ScreenHeight;
var ScreenWidth;
var kUserEmail;
var kUserPassword;
var kUserPhone;
var kUserNickName;
var kUserName;
var kUserPhotoUrl;
var kUserGoogleID;
var email;
var name;
var nickname;
var phone;
bool kLog = false;
var userPhotoUrl;
var isSignIn;