// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnj_B64nkoFbvi6QV4S6uI_ILi3Oyowe8',
    appId: '1:840856747821:web:4efa8860654e2b9026dda4',
    messagingSenderId: '840856747821',
    projectId: 'embelia-367713',
    authDomain: 'embelia-367713.firebaseapp.com',
    databaseURL: 'https://embelia-367713-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'embelia-367713.appspot.com',
    measurementId: 'G-7YMML0687G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHVGZq-ooJ3AERZtsch9SKmgWprRKnxww',
    appId: '1:840856747821:android:77436dbd78472a5726dda4',
    messagingSenderId: '840856747821',
    projectId: 'embelia-367713',
    databaseURL: 'https://embelia-367713-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'embelia-367713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRaTk7_mmuydYK_HBLGKKCdc8CBPDyprk',
    appId: '1:840856747821:ios:2f189f84089f8e1a26dda4',
    messagingSenderId: '840856747821',
    projectId: 'embelia-367713',
    databaseURL: 'https://embelia-367713-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'embelia-367713.appspot.com',
    androidClientId: '840856747821-68uj148d21kgdrbpbc82mhmcgp24pivh.apps.googleusercontent.com',
    iosClientId: '840856747821-bmd8a79hv3r3ikaqniv55id3e7ct2ouo.apps.googleusercontent.com',
    iosBundleId: 'com.pratyush.embelia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRaTk7_mmuydYK_HBLGKKCdc8CBPDyprk',
    appId: '1:840856747821:ios:2f189f84089f8e1a26dda4',
    messagingSenderId: '840856747821',
    projectId: 'embelia-367713',
    databaseURL: 'https://embelia-367713-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'embelia-367713.appspot.com',
    androidClientId: '840856747821-68uj148d21kgdrbpbc82mhmcgp24pivh.apps.googleusercontent.com',
    iosClientId: '840856747821-bmd8a79hv3r3ikaqniv55id3e7ct2ouo.apps.googleusercontent.com',
    iosBundleId: 'com.pratyush.embelia',
  );
}
